Sports_Schema = {'key': 'americanfootball_ncaaf',
                 'group': ' American Football',
                 'title': 'NCAAF',
                 'description': 'US College Football'
                }

Events_Schema = {'id': 'bda33adca828c09dc3cac3a856aef176',
                'sport_key': 'americanfootball_nfl',
                'commence_date': '2023-07-25',
                'commence_time': '18:45:00',
                'home_team': 'Tampa Bay Buccaneers',
                'away_team': 'Dallas Cowboys',
                'home_odds': {'bookie_key': 1.5,
                              'bookie_key': 1.5,
                              'bookie_key': 1.5},
                'away_odds': {'bookie_key': 1.5,
                              'bookie_key': 1.5,
                              'bookie_key': 1.5},
                'draw_odds': {'bookie_key': 1.5,
                              'bookie_key': 1.5,
                              'bookie_key': 1.5}
                }

Best_Odds_Schema = {'id': 'bda33adca828c09dc3cac3a856aef176',
                    'sport_key': 'americanfootball_nfl',
                    'commence_date': '2023-07-25',
                    'commence_time': '18:45:00',
                    'home_team': 'Tampa Bay Buccaneers',
                    'away_team': 'Dallas Cowboys',
                    'home_odds': {'best': [1.5, 'bookie_key', 'bookie_key'],
                                       'us': [1.5, 'bookie_key', 'bookie_key'],
                                       'us2': [1.5, 'bookie_key', 'bookie_key'],
                                       'uk': [1.5, 'bookie_key', 'bookie_key'],
                                       'au': [1.5, 'bookie_key', 'bookie_key'],
                                       'eu': [1.5, 'bookie_key', 'bookie_key']},
                    'away_odds': {'best': [1.5, 'bookie_key', 'bookie_key'],
                                       'us': [1.5, 'bookie_key', 'bookie_key'],
                                       'us2': [1.5, 'bookie_key', 'bookie_key'],
                                       'uk': [1.5, 'bookie_key', 'bookie_key'],
                                       'au': [1.5, 'bookie_key', 'bookie_key'],
                                       'eu': [1.5, 'bookie_key', 'bookie_key']},
                    'draw_odds': {'best': [1.5, 'bookie_key', 'bookie_key'],
                                       'us': [1.5, 'bookie_key', 'bookie_key'],
                                       'us2': [1.5, 'bookie_key', 'bookie_key'],
                                       'uk': [1.5, 'bookie_key', 'bookie_key'],
                                       'au': [1.5, 'bookie_key', 'bookie_key'],
                                       'eu': [1.5, 'bookie_key', 'bookie_key']}
                    }

Arbitrage_Schema = {'id': 'bda33adca828c09dc3cac3a856aef176',
                    'sport_key': 'americanfootball_nfl',
                    'commence_date': '2023-07-25',
                    'commence_time': '18:45:00',
                    'home_team': 'Tampa Bay Buccaneers',
                    'away_team': 'Dallas Cowboys',
                    'best': {'home_odds': [1.5, 'bookie_key', 'bookie_key'],
                             'away_odds': [1.5, 'bookie_key', 'bookie_key'],
                             'implied_probabiliy': '0.97'},
                    'us': {'home_odds': [1.5, 'bookie_key', 'bookie_key'],
                           'away_odds': [1.5, 'bookie_key', 'bookie_key'],
                           'implied_probabiliy': '0.97'},
                    'us2': {'home_odds': [1.5, 'bookie_key', 'bookie_key'],
                            'away_odds': [1.5, 'bookie_key', 'bookie_key'],
                            'implied_probabiliy': '0.97'},
                    'uk': {'home_odds': [1.5, 'bookie_key', 'bookie_key'],
                           'away_odds': [1.5, 'bookie_key', 'bookie_key'],
                           'implied_probabiliy': '0.97'},
                    'au': {'home_odds': [1.5, 'bookie_key', 'bookie_key'],
                           'away_odds': [1.5, 'bookie_key', 'bookie_key'],
                           'implied_probabiliy': '0.97'},
                    'eu': {'home_odds': [1.5, 'bookie_key', 'bookie_key'],
                           'away_odds': [1.5, 'bookie_key', 'bookie_key'],
                           'implied_probabiliy': '0.97'}
                    }

Completed_Events_Schema = {'id': 'bda33adca828c09dc3cac3a856aef176',
                           'sport_key': 'americanfootball_nfl',
                           'commence_date': '2023-07-25',
                           'commence_time': '18:45:00',
                           'home_team': 'Tampa Bay Buccaneers',
                           'away_team': 'Dallas Cowboys',
                           'home_team_score': '47',
                           'away_team_score': '25',
                           'outcome': 'home_team'
                           }
